### ISSUE TITLE
failed to register layer: Error processing tar file(exit status 1): write /usr/lib/x86_64-linux-gnu/libmysqlclient.so.18.0.0: no space left on device

### ISSUE THREAD

**Issue by nford** [dannylinden/aws-lambda-php#4]
$ docker build -t lambda-php-unittest -f Dockerfile.TestLambdaApp .
Sending build context to Docker daemon 24.78 MB
Step 1/7 : FROM node:argon
argon: Pulling from library/node
5040bd298390: Already exists 
fce5728aad85: Pull complete 
76610ec20bf5: Pull complete 
52f3db4b5710: Extracting [==================================================>] 129.8 MB/129.8 MB
7e5867712a67: Download complete 
563b602246dd: Download complete 
639d8afc9c2e: Download complete 
failed to register layer: Error processing tar file(exit status 1): write /usr/lib/x86_64-linux-gnu/libmysqlclient.so.18.0.0: no space left on device

**Comment by cdumitras** [comment]
This seems like the disk is full and not a issue

**Comment by nford** [comment]
My bad sorry, I initially thought there was an issue with the docker container
